config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :pokemons, only: [:index, :new, :create]
  resources :sales, only: [:index, :update, :destroy]

  post 'sales/create', action: :create, controller: 'sales'

  get 'user/acquisitions', action: :acquisitions, controller: 'sales'
  get 'user/sales', action: :sales, controller: 'sales'

  root "home#index"

  resources :users, to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_many :sales

  validates :name, :base_experience, :sprite_url, presence: true

  def is_for_sale
    sales.where(to_user_id: nil).exists?
  end

  def current_value
    sat_usd_rate = Rate.sat_to_usd_rate.rate

    base_experience * sat_usd_rate
  end
end

app/models/rate.rb
class Rate < ApplicationRecord
  class << self
    def sat_to_usd_rate
      rate = Rate.where('created_at >= ?', 10.minutes.ago).take

      unless rate
        rate = get_updated_sat_to_usd_rate
      end

      rate
    end

    private

    def get_updated_sat_to_usd_rate
      uri = URI("https://rest.coinapi.io/v1/exchangerate/BTC/USD")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(uri.path, {
        'Content-Type' => 'application/json',
        'X-CoinAPI-Key' => ENV["COIN_API_KEY"]
      })
      response = http.request(request)

      return if response.code != '200'

      satoshi = JSON.parse(response.body)['rate'].to_f / 100000000
      rate = Rate.new(rate: satoshi)
      rate.save!

      rate
    end
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :from_user, class_name: "User"
  belongs_to :to_user, class_name: "User", optional: true
  belongs_to :pokemon
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :pokemons
  has_many :sales, class_name: "Sale", foreign_key: "from_user"
  has_many :acquisitions, class_name: "Sale", foreign_key: "to_user"

  def total_wallet_value
    sat_usd_rate = Rate.sat_to_usd_rate.rate

    pokemons.sum(:base_experience) * sat_usd_rate
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @last_sales = Sale.where('to_user_id IS NOT null').last(10)
    @last_offers = Sale.where('to_user_id IS null').last(10)
    @last_sat_usd = Rate.sat_to_usd_rate
    @total_wallet_value = current_user.total_wallet_value if current_user
    @last_rates = Rate.last(10)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pokemon, only: %i[ destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.where(user: current_user).order(:updated_at).all
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)
    pokemon = get_pokemon_by_name(pokemon_params[:name])

    unless pokemon
      return redirect_to new_pokemon_url, status: :unprocessable_entity, alert: 'Pokemon not found'
    end

    @pokemon.name = pokemon['name']
    @pokemon.base_experience = pokemon['base_experience']
    @pokemon.sprite_url = pokemon['sprites']['front_default']
    @pokemon.user = current_user

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to pokemons_url, notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    def pokemon_params
      params.require(:pokemon).permit(:name, :user_id)
    end

    def get_pokemon_by_name(name)
      uri = URI("https://pokeapi.co/api/v2/pokemon/#{name}/")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(uri.path, {'Content-Type' => 'application/json'})
      response = http.request(request)

      return nil if response.code != '200'

      JSON.parse(response.body)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!, only: %i[ acquisitions sales create update destroy ]
  before_action :set_sale, only: %i[ update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.where(to_user_id: nil).all
  end

  def acquisitions
    @sales = Sale.where(to_user: current_user).all
  end

  def sales
    @sales = Sale.where(from_user: current_user).all
  end

  # POST /sales or /sales.json
  def create
    pokemon = current_user.pokemons.find_by(id: params['pokemon_id'])

    unless pokemon
      return redirect_to root_path, status: :unprocessable_entity, alert: 'Pokemon not found'
    end

    @sale = Sale.new(from_user: current_user, pokemon: pokemon)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to pokemons_url, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    pokemon = @sale.pokemon
    pokemon.user = current_user
    @sale.to_user = current_user

    respond_to do |format|
      if @sale.save && pokemon.save
        format.html { redirect_to sales_path, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { redirect_to sales_path, status: :unprocessable_entity, alert: "Sale was unsuccessfully updated." }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to user_sales_path, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_sale
      @sale = Sale.find(params[:id])
    end

    def sale_params
      params.permit(:from_user_id, :to_user_id, :pokemon_id)
    end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_last_rates.html.erb
<div class="cointainer">
  <h2 class="mb-4">Last exchange rates</h2>

  <ul class="list-group">
    <% last_rates.each do |rate| %>
      <li class="list-group-item">

        <strong>Value: </strong><%= number_to_currency(rate.rate, precision: 8) %>
        <strong>Time: </strong><%= rate.created_at.strftime("%d/%m/%Y at %H:%M") %>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/_offers_list.html.erb
<div class="cointainer">
  <h2 class="mb-4">Latest offers</h2>

  <ul class="list-group">
    <% offers.each do |offer| %>
      <li class="list-group-item">
        <strong>Name: </strong><%= offer.pokemon.name %>
        <strong>Value: </strong><%= offer.pokemon.base_experience %>
        <strong>From: </strong><%= offer.from_user_id %>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/_sales_list.html.erb
<div class="cointainer">
  <h2 class="mb-4">Latest sales</h2>

  <ul class="list-group">
    <% sales.each do |sale| %>
      <li class="list-group-item">
        <strong>Name: </strong><%= sale.pokemon.name %>
        <strong>Value: </strong><%= sale.pokemon.base_experience %>
        <strong>From: </strong><%= sale.from_user_id %>
        <strong>To: </strong><%= sale.to_user_id %>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/_satoshi_to_usd.html.erb
<div class="cointainer">
  <h2 class="mb-4">Satoshi to USD</h2>
  <h2 class="mb-4"></h2>

  <h4 class="mb-4">
    <strong>Exchange rate:</strong>
    <%= number_to_currency(last_sat_usd.rate, precision: 8) %>
  </h4>

  <% if user_signed_in? %>
    <h4 class="mb-4">
      <strong>Your wallet total:</strong>
      <%= number_to_currency(total_wallet_value, precision: 8) %>
    </h4>
  <% end %>

</div>

app/views/home/index.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-8">
    <div class="row row-cols-1 row-cols-md-2 g-4 mb-4">
      <%= render "satoshi_to_usd", last_sat_usd: @last_sat_usd, total_wallet_value: @total_wallet_value %>
      <%= render "last_rates", last_rates: @last_rates %>
      <%= render "offers_list", offers: @last_offers %>
      <%= render "sales_list", sales: @last_sales %>
    </div>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="alert-wrapper">
  <div class="alert <%= 'alert-danger' if alert %> <%= 'alert-primary' if notice %> alert-dismissible alert__stick-top fade show m-4" role="alert">
    <%= alert || notice %>

    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>

app/views/layouts/_avatar.html.erb
<% if user_signed_in? %>
  <a href="#" class="header__avatar--<%= type %>" data-bs-toggle="dropdown" aria-expanded="false">
    <%= image_tag "poketrainer.png", class: "rounded-circle", size: "48", alt: "Logged in profile picture" %>
  </a>
<% else %>
  <a href="#" class="header__avatar--<%= type %>" data-bs-toggle="dropdown" aria-expanded="false">
    <%= image_tag "avatar_placeholder.png", class: "rounded-circle", size: "48", alt: "Not logged in profile picture" %>
  </a>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <p class="lead">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </p>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li class="lead"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-danger">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "pokeball.png", class: "rounded-circle", size: "32", alt: "Project logo" %>
      <strong>PokeCoin</strong>
    <% end %>

    <%= render 'layouts/avatar', type: "mobile" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item mt-2 mb-2">
          <%= link_to "Pokemons", pokemons_path, class: "nav-link btn btn-link text-white" %>
        </li>

        <li class="nav-item mt-2 mb-2">
          <%= link_to "Offers", sales_path, class: "nav-link btn btn-link text-white" %>
        </li>
      </ul>
    </div>

    <%= render 'layouts/avatar', type: "desktop" %>

    <div class="header__dropdown">
      <ul class="dropdown-menu text-small" data-popper-placement="bottom-end">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Profile', edit_user_registration_path, class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to 'My acquisitions', user_acquisitions_path, class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to 'My sales', user_sales_path, class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to 'Pokemons', pokemons_path, class: "dropdown-item" %>
          </li>
          <li><hr class="dropdown-divider"></li>
          <li>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', new_user_session_path, class: "dropdown-item" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokecoin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="page-container">
      <%= render 'layouts/header' %>

      <% if alert || notice %>
        <%= render 'layouts/alert' %>
      <% end %>

      <div class="content-wrap">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= bootstrap_form_with(model: pokemon) do |f| %>
  <%= render "layouts/error_messages", resource: pokemon %>

  <%= f.text_field :name, placeholder: "Pokemon name", autocomplete: "name" %>

  <%= f.submit class: "btn btn-primary btn-lg w-100" %>
<% end %>

app/views/pokemons/_pokemon.html.erb
<div class="col">
  <div class="card h-100">
    <%= image_tag pokemon.sprite_url, class: "card-img-top", alt: "Pokemon front picture" %>

    <div class="card-body">
      <p class="card-text">
        <strong>Base experience:</strong>
        <%= pokemon.base_experience %>
      </p>

      <p class="card-text">
        <strong>Current value:</strong>
        <%= number_to_currency(pokemon.current_value, precision: 8) %>
      </p>
    </div>

    <% if !pokemon.is_for_sale %>
      <div class="card-footer">
        <%= button_to 'Put for sale', sales_create_path(pokemon_id: pokemon.id), method: :post, class: "btn btn-outline-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemons/index.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-10">
    <h2 class="mb-4">
      Pokemons
    </h2>

    <div class="mb-4">
      <%= link_to 'New pokemon', new_pokemon_path, class: "btn btn-outline-primary mb-4" %>

      <div class="row row-cols-1 row-cols-md-4 g-4 mb-4">
        <% @pokemons.each do |pokemon| %>
          <%= render pokemon %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pokemons/new.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      New pokemon
    </h2>

    <div class="mb-4">
      <%= render "form", pokemon: @pokemon %>
    </div>

    <%= link_to 'Back to pokemons', pokemons_path, class: "btn btn-outline-primary btn-lg w-100" %>
  </div>
</div>

app/views/sales/_sale.html.erb
<div class="col">
  <div class="card h-100">
    <%= image_tag sale.pokemon.sprite_url, class: "card-img-top", alt: "Pokemon front picture" %>

    <div class="card-body">
      <p class="card-text">
        <strong>Base experience:</strong>
        <%= sale.pokemon.base_experience %>
      </p>
    </div>

    <div class="card-body">
      <p class="card-text">
        <strong>From user:</strong>
        <%= sale.from_user_id %>
      </p>
    </div>

    <div class="card-body">
      <p class="card-text">
        <strong>To user:</strong>
        <%= sale.to_user_id %>
      </p>
    </div>

    <% if buy && current_user && sale.from_user_id != current_user.id %>
      <div class="card-footer">
        <%= button_to 'Buy', sale_path(sale), method: :put, class: "btn btn-primary w-100" %>
      </div>
    <% end %>

    <% if remove && !sale.to_user_id %>
      <div class="card-footer">
        <%= button_to 'Remove from sale', sale, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/sales/acquisitions.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-10">
    <h2 class="mb-4">
      My acquisitions
    </h2>

    <div class="mb-4">
      <div class="row row-cols-1 row-cols-md-4 g-4 mb-4">
        <% @sales.each do |sale| %>
          <%= render sale, buy: false, remove: false %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sales/index.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-10">
    <h2 class="mb-4">
      Offers
    </h2>

    <div class="mb-4">
      <div class="row row-cols-1 row-cols-md-4 g-4 mb-4">
        <% @sales.each do |sale| %>
          <%= render sale, buy: true, remove: false %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sales/sales.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-10">
    <h2 class="mb-4">
      My sales
    </h2>

    <div class="mb-4">
      <div class="row row-cols-1 row-cols-md-4 g-4 mb-4">
        <% @sales.each do |sale| %>
          <%= render sale, buy: false, remove: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>